complete -c gpv -l var -d "<gturl> | set the variable name and slicing parameters. "
complete -c gpv -l vf -d " | use variable whose name is included in the filename. "
complete -c gpv -l pry -d " | start pry after drawing the first figure. "
complete -c gpv -l auto_pry -d "<args> | automatically execute the given scripts like as in pry after drawing the first figure. "
complete -c gpv -l list -d " | execute gplist instead of any other options. "
complete -c gpv -l silent -d " | show only calculated values. do not show any messages. "
complete -c gpv -l parallel -d "[dim] | use parallel anyway. "
complete -c gpv -l help -d "[option_name] | show help. show help for a specific option when the option name is given (without '--'). "
complete -c gpv -l edit_ncatt -d "<ncatted_args> | edit netcdf's attribute by ncatted commands. "
complete -c gpv -l sequence -d "<sequence name> | execute sequence scripts defined in gpv_sequence.rb. "
complete -c gpv -l clrmap -d "<1- or filename> | set colormap to draw tone/contour. filename of DCL colormap is acceptable. "
complete -c gpv -l itr -d "<1-4,5-7,10-15,20-23,30-33> | set axis scale. default is 1. 1 : linear scale for x/y axis 2 : linear scale for x , log scale for y axis 3 : log scale for x , linear scale for y axis 4 : log scale for x/y axis "
complete -c gpv -l similar -d "<simfac,vxoff,vyoff> | (for 5<=itr<=7) set similarity parameters which are fed in DCL.grssim. "
complete -c gpv -l map_axis -d "<uxc,uyc,rot> | (for 10<=itr<=33) set mapping parameters which are fed in DCL.umpcnt. "
complete -c gpv -l map_radius -d "<radius> | (for itr>=20) set clipping radius (degree) around the tangential point. Deafault=90. "
complete -c gpv -l sateliteview -d "<distance> | simulate satelite view. use with --itr 30. <distance> should be given in planetary-radius-unit. "
complete -c gpv -l xcoord -d "<xcoord> | name of x-coordinate (use for associate coordinates) "
complete -c gpv -l ycoord -d "<ycoord> | name of y-coordinate (use for associate coordinates) "
complete -c gpv -l title -d "<title> | set title of figure "
complete -c gpv -l notitle -d " | do not print title. equivalent to --title ''  "
complete -c gpv -l aspect -d "<aspect> | set aspect ratio of Viewport. default is 2.0. "
complete -c gpv -l anim -d "<dim> | plot animation along <dim>. <dim> must be name of dimension. "
complete -c gpv -l anim_div -d "<num> | use with --anim to divide anim interval into <num>. "
complete -c gpv -l noannotate -d " | not draw annotations. "
complete -c gpv -l alternate -d " | enable to backing store. "
complete -c gpv -l nowait -d " | not wait for any actions if animate "
complete -c gpv -l smooth -d " | equal to --anlternate && --nowait "
complete -c gpv -l reverse -d " | plot animation reversible if animate "
complete -c gpv -l exch -d " | exchange(transpose) x/y axis. "
complete -c gpv -l map -d "<map_type> | plot map. itr number must be set. this option is neglect if itr number is 1-4. abailable map type is coast_world, border_world, plate_world, state_usa, coast_japan, pref_japan "
complete -c gpv -l time_ax -d "<nil|false|h|ymd> | specify type of calendar-type time axis: nil (=> auto slection) false (=> do not use the time axis even if the units of the axis is a time one with since field) h (=> like nil, but always use the hour-resolving datetime_ax method in dclext_datetime_ax.rb) ymd (=> like h but for y-m-d type using DCL.uc[xy]acl) "
complete -c gpv -l sldiv -d "<<y|t>,m,n> | split the drawing window into multiple panel. argument should be provied in DCL.sldiv form. e.g., --sldiv y,2,2 make 2x2 window. "
complete -c gpv -l scatter -d "[xtitle,ytitle] | make scatter plot with provided 2 gturls. 1st and 2nd gturls will be used for x- and y-axes, respectively. titles of x- and y- axes can be specified by arguments xtitle,ytitle (optional) range of each axis can be specified by option --range [xmin:xmax,ymin:ymax] format. with --line option, lines between marks are drawn. "
complete -c gpv -l color_scatter -d "[xtitle,ytitle] | make color scatter plot with provided 3 gturls. 1st and 2nd gturls are used for x- and y-axes, respectively. 3rd gturl is used for color of marks. titles of x- and y- axes can be specified by arguments xtitle,ytitle (optional) range of each axis and color can be specified by option --range [xmin:xmax,ymin:ymax,zmin:zmax] format with --line option, lines between marks are drawn. "
complete -c gpv -l cot -d " | contour over tone. draw tone with 1st gturl and overplot contour with 2nd gturl. "
complete -c gpv -l histogram -d "[arg] | draw 1D histogram, probability density function, or their cumulative plots. when argument 'ratio' is given, histogram are shown in %. when argument 'sphere' is given, histogram are shown in area % consdiring spherical area weight for lat-lon grid data. when argument 'pdf' is given, values are converted to prbability density function. when commulative_up is given, cumulative plot towords higher direction is drawn. when commulative_down is given, cumulative plot towords lower direction is drawn. these args can be used at the same time by comma separation such as 'sphere,pdf'. options '--int -n' and '--range xmin:xmax[,ymin:ymax]' can be used to set bins number and range. options '--exch', '--title', and '--overplot n' also can be used. option '--line' can be used with to plot in line. "
complete -c gpv -l histogram2D -d "[any] | draw 2D histogram with two gtulrs. if any argument is given, histogram are shown in percentage (%) not in numbers. options '--int -n' and '--range xmin:xmax[,ymin:ymax]' can be used to set bins number and range. options '--sint [-]n' and '--srange xmin:xmax' can be used to set tone interval[number] and range. options '--exch' and '--title' also can be used. "
complete -c gpv -l rmap -d "<dim> | draw 2D map of correaltion between 1st and 2nd gturls along <dim> axis. <dim> can be axis name (string) or dimension number (integer), but only one axis is acceptable. "
complete -c gpv -l linearline -d "<arg> | draw linear line expressed bay <arg>. <arg> should be 'x=<value>', 'y=<value>', 'x=y', or 'y=x', where <value> is integer or float. multiple lines can be drawn by setting multiple args separated by comma, such as 'x=0,y=0'. "
complete -c gpv -l land -d " | mask data with land info, https://www.ncl.ucar.edu/Applications/Data/cdf/landsea.nc. you need to download landsea.nc and place it on correct dir. "
complete -c gpv -l ocean -d " | mask data with ocean info, https://www.ncl.ucar.edu/Applications/Data/cdf/landsea.nc. you need to download landsea.nc and place it on correct dir. "
complete -c gpv -l line -d " | make line plot forced. (about first 1D) "
complete -c gpv -l mark -d " | make mark plot forced. (about first 1D) "
complete -c gpv -l index -d "<index_num> | set DCL line index, which set the color/thickness of the line primitive. please see DCL documents. "
complete -c gpv -l type -d "<type_num> | set line type. "
complete -c gpv -l overplot -d "<num> | set number of lines on each figure with color. use with --nocolor if you want to distinguish by line type. "
complete -c gpv -l nocolor -d " | draw without using color. "
complete -c gpv -l right_axis -d " | use with '--overplot 2' and draw 2nd y-axis in right side for 2nd gturl. range of 2nd y-axis can be specified by --range left_min1:left_max,right_min:right_max. "
complete -c gpv -l top_axis -d " | 使い方を忘れた... "
complete -c gpv -l overplot_rm -d "<span> | overplot the running mean with thick line. running mean span is required. "
complete -c gpv -l overplot_stddev -d " | overplot the mean +/- stddev (like errorbars). this must be used with '--mean' option. "
complete -c gpv -l nocont -d " | make tone plot, without contour. "
complete -c gpv -l noshade -d " | make contour plot, without tone. "
complete -c gpv -l log_int -d " | use log interval in contour/tone. "
complete -c gpv -l range -d "<min:max> | set min/max value for contour/tone/line/mark plot. min or max must be set. "
complete -c gpv -l crange -d "<min:max> | set min/max value for contour plot. this is more dominant than --range "
complete -c gpv -l srange -d "<min:max> | set min/max value for tone plot. this is more dominant than --interval/int "
complete -c gpv -l interval -d "<num> | set interval value for contour/tone plot. set the number of lines if you set negative value. "
complete -c gpv -l cint -d "<num> | set interval value for contour plot. this is more dominant than --interval/int "
complete -c gpv -l sint -d "<num> | set interval value for tone plot. this is more dominant than --interval/int. "
complete -c gpv -l levels -d "<val1,val2,val3,...> | set values of contour/tone levels. "
complete -c gpv -l clevels -d "<val1,val2,val3,...> | set values of contour levels. "
complete -c gpv -l slevels -d "<val1,val2,val3,...> | set values of tone levels. "
complete -c gpv -l patterns -d "<pattern1,pattern2,..> | set each patterns for tone plot. "
complete -c gpv -l tone -d "<a|e|f|b|c> | set tone subroutine: a (=> tone routine is selected automatically depending on the datasize) e (=> DCL.uetone is used) f (=> DCL.uetonf is used) b (=> DCL.uetonb is used) c (=> DCL.uetonc is used) "
complete -c gpv -l udsfmt -d "<strings> | change contour label format. see UDCNTR/DCL manual for the format. "
complete -c gpv -l nocolorbar -d " | do not draw color bar. "
complete -c gpv -l nozero -d " | do not draw zero contour. "
complete -c gpv -l nodraw -d " | do not draw any figures. "
complete -c gpv -l file -d "<png|eps|pdf[,filename]> | raw in file with given format. available formats are png, eps, and pdf. "
complete -c gpv -l crop -d " | crop (trim) output png or pdf. "
complete -c gpv -l title_array -d "<string,string,...> | set multiple titles given as --title_array hoge,foo,bar; this gives the title 'hoge' to the 1st figure, 'foo' to the 2nd one, and 'bar' to the 3rd one. "
complete -c gpv -l miscindex -d "<num> | set line index (color and width) of title, label, frame, etc. "
complete -c gpv -l index_array -d "<index1,index2,...> | set array of index used for 1st, 2nd,... lines/mark. "
complete -c gpv -l type_array -d "<index1,index2,...> | set array of type index used for 1st, 2nd,... lines/mark. "
complete -c gpv -l subtitle -d "<string> | set subtitle, which locates just below the title and is common for multple figures. "
complete -c gpv -l irange -d "<min:max> | same as --range but with +/- infinity for both boundaries. use with --int is recomended. "
complete -c gpv -l xrange -d "<min:max> | set the range of x-axis for line plot and 2D plot. "
complete -c gpv -l yrange -d "<min:max> | set the range of y-axis for line plot and 2D plot. "
complete -c gpv -l clr_range -d "<min:max> | set color range. maximum range is 10:99. default is 15:94. "
complete -c gpv -l wm -d " | alias for --itr 10 --map coast_world --nocont. "
complete -c gpv -l size -d "<num> | set the size factor of x-window (default: 1.25) "
complete -c gpv -l fullcolor -d "<1|2> | draw fullcolor fig. --fullcolor 1 draws with 1 var. --fullcolor 2 draws with 2 vars; 1st gturl is used for color (hue) and 2nd one is used for brightness (value). option of --range xmin:xmax,ymin:ymax can be used. "
complete -c gpv -l step -d " | make 1D line plot to step shape. "
complete -c gpv -l zerocenter -d "[max] | set y-axis center in line plot figure to zero. "
complete -c gpv -l vector -d " | draw a vector plot. When 2 gturls are given, 1st one and 2nd one are used for x- and y-components of the vectors. When 3 or 4 gturls are given, 2nd one and 3rd one are used for x- and y-components of the vectors, and tone of 1st one and counter of 4th one are overlaid. If the 1st dim is lon or lat and the 2nd dim is not lon or lat, vectors are scaled by the geometry aspect ratio. "
complete -c gpv -l vfact -d "<factor> | use with '--vector' to change the size of the vector by <factor>. "
complete -c gpv -l vint -d "<int> | use with '--vector' to change the gird-interval to draw vectors. "
complete -c gpv -l vkeep -d " | use with '--vector' to keep the size of unit vector as that of the first plot. "
complete -c gpv -l nolegend -d " | do not draw legend of line plot. "
complete -c gpv -l textbox -d "<text,num,[l|c]> | draw textbox, legends, and/or color bar in frame #<num>. "
complete -c gpv -l fact -d "<fact> | factor for charcter size "
complete -c gpv -l xmean -d " | draw line plot of mean along x-axis on the right hand side of the tone/contour plot. "
complete -c gpv -l ymean -d " | draw line plot of mean along y-axis below the tone/contour plot. "
complete -c gpv -l maskshading -d "<gturl,maskval,ipat> | draw a mask for values less than or equal to maskval (optional; defalult is 0) with given gturl (optional; default is same as previously drawn GPhys) by ipat pattern number (optional; defalult is 1515). "
complete -c gpv -l nolabels -d " | do not draw labels. "
complete -c gpv -l fill -d " | fill regions between plotted line and zero (or min or max) line. if histogram, fill the boxes. "
complete -c gpv -l lwf -d "<float> | set line with factor for pdf drawing. defalut is 999, which looks like DISP drawing. "
complete -c gpv -l axis_options -d "<var1=val1,var2=val2,..> | set some axis options of USPACK (i.e., xoff/yoff, xfac/yfac, dxt/dyt, dxl,dyl) "
complete -c gpv -l bothsides -d " | draw bothsides of the planet when itr = 30 "
complete -c gpv -l xint -d "<xlabelint[:division]> | set x-axis' label-tickmark interval and number of number of division between two label-tickmarks e.g., --xint 10:5 draws label interval with 10 and sub-tickmark interval of 2 (=10/5). "
complete -c gpv -l yint -d "<ylabelint[:division]> | same as --xint but for y-axis. "
complete -c gpv -l panelfit -d "[margin] | force the figure to fit into the panel. margin can be given by ratio [0-1]. "
complete -c gpv -l zoomin -d "<xaxis=xmin:xmax,yaxis=ymin:ymax> | to be written "
complete -c gpv -l plot_particles -d "<gturl of particles> | overplot particles "
complete -c gpv -l mean -d "<dim> | mean along axis <dim>. "
complete -c gpv -l stddev -d "<dim> | standard deviation along axis <dim>. "
complete -c gpv -l eddy -d "<dim> | deviation from mean along axis <dim>. "
complete -c gpv -l diff -d " | calculate 1st gturl - 2nd gturl "
complete -c gpv -l divide -d " | calculate 1st gturl / 2nd gturl "
complete -c gpv -l add -d " | calculate the sum of multiple variables. "
complete -c gpv -l operation -d "<math_func> | operation of the specified math function on the data. <math_func> should be a math function with one argument such as log10, sqrt, sin, etc. "
complete -c gpv -l running_mean -d "<dim>:<span>[:<skip>][,<dim>:<span>[:<skip>]]> | calculate the running mean along <dim> with a window of <span>. multiple dims are not supported. if integer <skip> is given, the date thinning is performed to the running mean. for example, --rm t,12,12 to monthly data gives annual mean series (one value per year). "
complete -c gpv -l global_mean -d " | calculate the global mean considering the weight along latitude. dims of longitude and latitude must be the 1st and 2nd dims, respectivly. "
complete -c gpv -l ensemble_mean -d "[num] | calculate the ensemble mean. you must provide two or more gturls whose size and dimension are same. if <num> is given, ensemble mean will be calculated for each <num> gturls. if 'concat' is given for <num>, provided gturls are concatenated along new dimension 'member'. "
complete -c gpv -l normalize -d "[ |mean|float] | normalize data by initial (when no arg.) or mean or given value when data is one-dimension. normalization for other data is not implemented yet. "
complete -c gpv -l lowpass -d "<dim>,<wn> | apply lowpass filter to <dim>-th dimension with wavenumber <wn> using fft. i.e., this cut off the wavenumbers greater than <wn>. <dim> must be integer. dimname is not supported yet. when use with --sht option, spherical harmonic trasnformation is applied. in that case, ARGUMENT should be only <wn>, which is total wavenumber. 1st and 2nd dimension must be lon and lat. "
complete -c gpv -l highpass -d "<dim>,<wn> | apply highpass filter to <dim>-th dimension with wavenumber <wn> using fft. i.e., this cut off the wavenumbers less than <wn>. <dim> must be integer 0, 1, 2, or 3. dimnames and dim > 3 are not supported yet. when use with --sht option, spherical harmonic trasnformation is applied. in that case, ARGUMENT should be only <wn>, which is total wavenumber. 1st and 2nd dimension must be lon and lat. "
complete -c gpv -l power_spectra -d "<dim[,any]> | calculate power spectra using fft along <dim>-th dimension. by default, wavenumber is used for axis. if any argument is given after comma, wavelength or period is used for axis. "
complete -c gpv -l derivative -d "<dim> | calculate the derivative alog axis <dim>. GPhys.threepoint_O2nd_deriv is used. "
complete -c gpv -l srot -d " | calculate rotation on sphere with 1st gturl and 2nd gturl. radius can be set by --radius. "
complete -c gpv -l sdiv -d " | calculate divergence on sphere with 1st gturl and 2nd gturl. radius can be set by --radius. "
complete -c gpv -l sht -d " | use spherical_harmonics_next module for srot, sdiv. "
complete -c gpv -l uvcomp -d " | calculate rot/div components of u/v. Output component should be given by nil, u_rot, u_div, v_rot, or v_div. "
complete -c gpv -l HKE -d " | calculate horizontal Kinetic energy with 1st gturl and 2nd gturl. "
complete -c gpv -l integrate -d "<dims> | calculate integration along <dims>. "
complete -c gpv -l sum -d "<dims> | calculate sum along <dims>. "
complete -c gpv -l addingup -d "<dim>[,<dim>,...]> | adding up values along <dim>; i.e., val[i] = val[0..i].sum "
complete -c gpv -l max -d "<dims> | max values along axis <dims>. "
complete -c gpv -l min -d "<dims> | min values along axis <dims>. "
complete -c gpv -l ES -d "[total|rot|div][,vor_div_given] | calculate Horizontal Kinetic Energy Spectra from U given as 1st gturl and V given as 2nd gturl. output total, rot, and/or div component. if 'vor_div_given' is given, 1st and 2nd gturls must be Vor and Div, respectivly, and they will be used for calculation (faster). "
complete -c gpv -l wnf_analysis -d "<sym|asym|bg|sym/bg|asym/bg|log_sym/bg|log_asym/bg> | calculate time-space spectra following Wheeler and Kiladis (1999) name of component to be output has to be given. "
complete -c gpv -l mvo -d "<mathematical operation> | mathematical operation for multiple gturls. For mathematical operation, 1st gturl must be indicated by 'x', 2nd by 'y', 3rd by 'z', 4th by 'u', 5th by 'v', 6th by 'w'. This cannot treat vars more than 6. Also, this cannot be used repeatedly. "
complete -c gpv -l mvo_only -d " | use with '--mvo' to execute 'multi variable operation' only. "
complete -c gpv -l cut -d "<dimname=pos1[:pos2[:thinning_intv]][,dimname=…]:  > | apply cut, slice, and/or thinning after mathmatical operation. "
complete -c gpv -l rank_conserving -d " | conserve all ranks when cut/slice "
complete -c gpv -l radius -d "<raidus> | set planetary radius. "
complete -c gpv -l Omega -d "<Omega> | set planetary rotation rate [s-1]. "
complete -c gpv -l rename -d "<varname> | rename the output variable name by <varname>. if --long_name is not used, 'long_name' is also renamed. "
complete -c gpv -l long_name -d "<long_name> | rename the output variable 'long_name' by <long_name>. "
complete -c gpv -l regrid -d "<latgrid_num> | interpolate to the Gausian latitude and cooresponding longitude. number of lat-grid points is required. "
complete -c gpv -l GLAT -d "[num] |  "
complete -c gpv -l read_csv -d "<num> | read csv file. the first column is used for the axis and the other columns are used for data values. <num> specifies how many data columns you want to read. "
complete -c gpv -l composite -d "<dim>,<span>,<skip> | if <skip> is not given or zero, calculate mean with interval <span>. i.e., --composite time,12 calculates mean of each month from monthly mean data. if <skip> is given, calculate composite mean for dimension <dim> with length <span> with interval of <skip>. i.e., --composite time,3,9 calculates mean for time=0,1,2,12,13,14,24,... this can be used to calculate seasonal mean such as DJF from mounthly mean data. "
complete -c gpv -l split_axis -d "<dim,span,[newaxisname]> | split the <dim> axis with <span>. for example, --split_axis time,12 applied to monthly data splits the time axis to year and month axis. name of the new axis can be given by [newnaxisname] "
complete -c gpv -l calendar360 -d " | set the calendar type to '360_day calendar'. normally, this will be set automatically. "
complete -c gpv -l calendar365 -d " | set the calendar type to '365_day calendar'. normally, this will be set automatically. "
complete -c gpv -l flip_data -d "<dim[,dim,..]> | flip (turn over) the data and axis of <dim>th dimension. <dim> must by given by integer(s). "
complete -c gpv -l interpolate_pole -d " | extend the latitude axis to have grid points on each pole (-90/+90 deg), and interpolate the pole values by mean of values on surrounding grid points. this assumes the data has lon and lat in its first and second dimension, respectivly. "
complete -c gpv -l set_missing_value -d "[float] | replace the missing values to given value and validate then. default: 0.0. "
complete -c gpv -l ignoreunit -d " | ignore unit "
complete -c gpv -l set_assoc_coords -d "<gturl> | set <gturl> as an associate coordinate. "
complete -c gpv -l sig2p -d "<gturl of surface pressure> | transform sigma coordinate to pressure coordinate. gturl of surface pressure must be given. "
complete -c gpv -l sig2z -d "<gturl of Temperature> | transform sigma coordinate to z (not log_p) coordinate. gturl of Temperature must be given. "
complete -c gpv -l interpolate -d "<args> | interpolate after operations. <args> can be axis_name=90 or axis_name=[0,90,180,270] or axis_name=0:360:4 for example. 1) axis_name=90 style gives interpolation at the location and rank shrinks. 2) axis_name=[0,90,180,270] style gives interpolation for multiple location and use then as an axis. 3) axis_name=0:360:4 style similar to (2) but 0:360:4 means from 0 to 360 with separation of (360-0)/4. multiple interpolation is not supported yet. if axis_name is associate_coord, you can indicate the original dim by adding [dim] after axis_name, such as p[z]. "
complete -c gpv -l extrapolation -d " | enable extrapolation, when using --interpolate option. "
complete -c gpv -l unit -d "<unit> | set the operated variable's unit. "
complete -c gpv -l invalidation -d "<num or range> | invalidate the given value or range. "
complete -c gpv -l join -d " | join muliple gturls along with an axis whose values are continual across the gturls and are not duplicate. "
complete -c gpv -l extend_backward_along -d "<dim,len[,value]> | extend backward the object along <dim>-axis for <len> numbers with <value>. "
complete -c gpv -l thinning -d "<num> | data thinning by picking up data with <num> interval "
complete -c gpv -l nothinning -d " | prevent auto data thinning. "
complete -c gpv -l read_fits -d " | read fits format image. automatically added if file extension is .fits. (RubyFits required) "
complete -c gpv -l offset -d "<float> | offset the data by <float>. "
complete -c gpv -l cyclic_extension -d "<dim:num[,dim:num]> | extend the data along <dim> with <num> number cyclically. e.g., --cyclic_extension x:4,y:4. "
complete -c gpv -l axis_units_name -d "<axdim:unit[:axname:operation][,axdim:unit:axname:operation]> | change unit (and name) of axis. multiple axes can be given as --axis_units_name ax0:deg:lon,ax2:km:height:/1000 for example. mathematical operation can be applied to the axis values. "
complete -c gpv -l replace_axis -d "<axN:val1,val2,val3,...> | replace the value of the axis <axN> (N is 0, 1, 2,...) with given Array [val1, val2, val3, val4,...] "
complete -c gpv -l zonal_shift -d "<speed at equator in m/s> | shift entire field zonally as it is advected by the solid body rotation of <speed at equator in m/s>. "
complete -c gpv -l nc -d "[outfilename] | output operated GPhys object as NetCDF file. output file name can be specified. Default name is 'out.nc'. if used with '--anim', GPhys object for last shown figure is outputtedd. "
complete -c gpv -l nc4 -d "[outfilename] | output operated GPhys object as NetCDF ver 4 with compression. may take longer time to write out. output file name can be specified. Default name is 'out.nc'. "
complete -c gpv -l nc4a -d "[outfilename] | output operated gphys continually with along time dim. "
complete -c gpv -l csv -d "[outfilename] | output operated GPhys object (1 dim only) as CSV file. output file name can be specified. Default name is 'out.csv'. if used with '--anim', GPhys object for last shown figure is outputtedd. "
complete -c gpv -l produce -d "<something> | produce <something>. <something> can be 'solar_zenith_angle' "
complete -c gpv -l output_assoc_coords -d " | use with --nc4 or --nc to output associate coordinate as netcdf file. "
complete -c gpv -l gif -d " | output gif animation. this must be used with --anim and --file png options. "
complete -c gpv -l mp4 -d "[number of frames per second] | output mp4 animation. frame rate can be given. this must be used with --anim and --file png options. "
complete -c gpv -l ntype -d "<type> | convert type of values. <type> should be 'sfloat', 'float', etc. "
complete -c gpv -l particle_advection -d "<tdiv=num x0,y0,z0 x1,y1,z1 x2:x3:xn,y2:y3:yn,z2:z3:zn> | perform particle advection. 1st, 2nd, 3rd gturl must be u, v, w, with lon, lat, z, and time axis. tdiv=num is the number for time interval to be devided for lagrangian tracing. E.g., When u data have 1 day interval, tdiv=24 make the lagrangian tracing by 1 hour interval. Inital location of a single particle can be given by x1,y1,z1. Expression like x2:x3:xn,y2:y3:yn,z2:z3:zn gives particles in a mesh begin with x2 and end at x3 and number of division is xn. Particle data will be output as 'particles.nc'.  "
